### ISSUE TITLE
Duplicate item (`REC-xml-19980210`)

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-data-w3c#5]
This item is present twice in the source (scroll down through data):

https://dev.bibxml.org/get-one/by-docid/?doctype=W3C&docid=W3C+REC-xml-19980210&format=bibxml

It’s not supposed to be a problem, since apps like BibXML service can address these by merging items. However, it’s difficult to do right: e.g., currently on the page above you can see that contributors are duplicated, since it’s very difficult to test Relaton contributors for whether they refer to the same person.

**Comment by ronaldtse** [comment]
It looks like that the two items are already separated as "series" (REC-xml-1998) vs "item" (REC-xml-19980210).

<img width="499" alt="Screenshot 2022-07-04 at 1 07 13 PM" src="https://user-images.githubusercontent.com/11865/177079863-c701d18a-e674-4926-a783-1f7cc76b84b7.png">

I am unsure why we have "REC-xml-1998" as a series though, because the series should be "REC-xml"?

Ping @andrew2net

**Comment by andrew2net** [comment]
> I am unsure why we have "REC-xml-1998" as a series though, because the series should be "REC-xml"?

@ronaldtse we have the "REC-xml-1998" in the static dataset https://github.com/relaton/relaton-w3c/blob/main/data/reference.W3C.REC-xml-1998.xml
The BibXML parser makes docnumber "REC-xml-1998" from the anchor "W3C.REC-xml-1998" and then creates the filename. Should we change the anchor to "W3C.REC-xml-19980210 in the dataset?

**Comment by ronaldtse** [comment]
> we have the "REC-xml-1998" in the static dataset

We need to remove these files (https://github.com/relaton/relaton-w3c/tree/main/data) now that we have the historic dataset, because the bibxml-service is reliant on relaton-w3c to obtain the authoritative data. Those files were originally from bibxml.

**Comment by ronaldtse** [comment]
For those unfamiliar with the current issue:
1. relaton-w3c includes a set of static files originating from IETF bibxml on W3C, because those W3C references are about withdrawn documents, and they are not available from W3C's authoritative dataset. (relaton/relaton-w3c#15)
2. relaton-w3c now parses all W3C historic information we obtained from archive.org (relaton/relaton-w3c#24), so we should technically cover all the files from relaton/relaton-w3c#15.
3. The above "duplicated item" can happen because of duplication between these two datasets.
